# Generated by Django 3.1.7 on 2022-02-16 09:31

import PosterApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PosterApp', '0003_auto_20220216_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userpic',
            field=models.ImageField(default='users/default-user-image.png', upload_to=PosterApp.models.user_dir_path),
        ),
    ]
