# Generated by Django 3.1.7 on 2022-02-16 11:49

import PosterApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PosterApp', '0005_post_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformpost',
            name='media',
            field=models.FileField(null=True, upload_to=PosterApp.models.platform_post_dir_path),
        ),
        migrations.AddField(
            model_name='platformpost',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
